#ifndef AUTOMATIC_GARDEN_SYSTEM_CONFIGS_H
#define AUTOMATIC_GARDEN_SYSTEM_CONFIGS_H

#include "private.h"

#define SOIL_MOISTURE_ANALOG_PIN 17

#define GROW_LAMP_PIN 16

#define RED_LIGHT_PIN 14
#define GREEN_LIGHT_PIN 12
#define BLUE_LIGHT_PIN 13


#include "defaults.h"

#endif //AUTOMATIC_GARDEN_SYSTEM_CONFIGS_H
